
version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.PERSONAL_GIT_TOKEN}}
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    # Remove this after the repo is turned public.
    registries: "*"
    # Remove this after the repo is turned public.
    insecure-external-code-execution: allow
    # Check for updates once a week
    schedule:
      interval: "weekly"
    target-branch: "main"
