cfg = {
    "database": "sample",
    "feature_types": ["Continuous", "Categorical", "Derived"],
    "feature_names_type": {
        "cont_0": 0,
        "cont_1": 0,
        "cont_2": 0,
        "cont_3": 0,
        "cont_4": 0,
        "cont_5": 0,
        "cont_6": 0,
        "cont_7": 0,
        "cont_8": 0,
        "cont_9": 0,
        "cat_0": 1,
        "cat_1": 1,
        "cat_2": 1,
        "cat_3": 1,
        "cat_4": 1,
        "cat_5": 1,
        "cat_6": 1,
        "cat_7": 1,
        "cat_8": 1,
        "cat_9": 1,
    },
    "categorical_feature_names": [
        "cat_0",
        "cat_1",
        "cat_2",
        "cat_3",
        "cat_4",
        "cat_5",
        "cat_6",
        "cat_7",
        "cat_8",
        "cat_9",
    ],
    "label_name": ["target"],
}
